from palworld_pal_editor.api.player import player_blueprint
from palworld_pal_editor.api.save import save_blueprint
from palworld_pal_editor.api.pal import pal_blueprint
from palworld_pal_editor.api.auth import auth_blueprint
from palworld_pal_editor.api.batch import batch_blueprint
from palworld_pal_editor.api.preset import preset_blueprint
from palworld_pal_editor.api.arena import arena_blueprint
from palworld_pal_editor.api.remote import remote_blueprint
from palworld_pal_editor.api.json_editor import json_editor_blueprint
from palworld_pal_editor.api.migration import migration_blueprint
